### ISSUE TITLE
Type of proxy

### ISSUE THREAD

**Issue by WexLab** [OGSegu/Twitch-View-Bot#1]
Привет, я посмотрел твою программу очень хорошая работа. Я сам пытался сделать такого бота, но где-то в 2019 году он престал работать, и собственно сколько я не парился он не работает. Я затестил твою программу через IntelliJ IDE и поюзал разные прокси, но эффекта так и не получил, не подскажешь какие прокси ты используешь для получения результата?

**Comment by OGSegu** [comment]
Привет, тебе нужны хорошие HTTPS прокси.
