### ISSUE TITLE
Gradlew build fail

### ISSUE THREAD

**Issue by 7ekhed** [OGSegu/Twitch-View-Bot#13]
Open Gradlew.bat, begins to run, fails, closes. Why is this?

**Comment by 7ekhed** [comment]
Edit to this, it DOES in fact give an error,

java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by OGSegu** [comment]
You need Java 11+
