### ISSUE TITLE
Luminati proxies intergrate

### ISSUE THREAD

**Issue by nick0zer** [OGSegu/Twitch-View-Bot#15]
Im trying to run the bot with luminati proxy format but Im getting bad proxy error

luminati proxy format:

zproxy.lum-superproxy.io:22225:lum-customer-c_e6xxxxx-zone-zone1-ip-xxx.xx.169.76:password

**Comment by OGSegu** [comment]
login: password proxies are not supported. As I remember you can add your IP to whitelist to use proxy without auth.
