### ISSUE TITLE
Can't choose proxy file

### ISSUE THREAD

**Issue by jackharl** [OGSegu/Twitch-View-Bot#18]
Hello

I am trying to run this on a ubuntu machine, i set up everything it needs and i can ran the program but when i try to load in proxy file i just can't see the file that i created.

I created the proxy file with the `touch `command.

Inside the file proxies are listed like this:

xxxx:xxx
xxxx:xx
xxxx:xxxx
etc.

**Comment by jackharl** [comment]
Hey

I managed to put up the proxies but i can't send viewers

**Comment by OGSegu** [comment]
Then it means, that proxies are bad

**Comment by jackharl** [comment]
Nope, program says viewers sent(22) but doesn't send it

**Comment by jackharl** [comment]
Proxies work too

**Comment by jackharl** [comment]
Also it would be nice if you put all of the working proxies in a seperate file so it could be easier to making lists

**Comment by OGSegu** [comment]
Can't really say which proxy will work with Twitch, probably they have got huge proxy black-list

**Comment by jackharl** [comment]
Can this work with ipv6 proxies ?
