### ISSUE TITLE
issues with building

### ISSUE THREAD

**Issue by toxicFAN** [OGSegu/Twitch-View-Bot#19]
Esentially i do have an issues while building ith gradlew.
Seems that java versions are in missmatch. I was trying to install various of versions on windows and linux and couldnt get through it.
My suggestion would be to create a docker image from a working environment. It could be so easy to deploy a container with all dependencies and sw versions.

Despite my suggestion any hint how to solve it?

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by OGSegu** [comment]
It should work for Java 11, are you sure that you have run it with right version?

**Comment by toxicFAN** [comment]
Thanks , i was tring to use java 8 as version 52 is java 8.
I tried with java 11 and now all works fine.

Additional question, what form should have proxy file? i dont see any reference :(

BTW, good that you have limited the no of views. obviously anyone can fork but this require some knowledge :)

**Comment by toxicFAN** [comment]
im running the SW on a virtual machine which runs on host under VPN.
I do have unlocked ports on my router for http 80 and 8080
while im running. it says that it started with 18 threads, no info that proxy is bad (i used to see this as well) but bottom line says requests sent 0.

Any suggestions how to solve this problem / configure?

**Comment by OGSegu** [comment]
Hard to say, because I didn't implement a log system. I will deal with that issue later

**Comment by toxicFAN** [comment]
got you. How should i typically configure the proxy then to make this running? Is proxy needed to make requests unique?
To be honest , dont know how to use it :)

**Comment by toxicFAN** [comment]
i opened ports on my virtual machine where bot is instaled. I opened 80 8080 and 443
I tried to use botj host machine IP and VM IP. All the time im getting "bad proxy"
Anyone any hints? :)

**Comment by toxicFAN** [comment]
could you please provide a sample proxy file? I still cant make it. What is the accepthed by the app syntac/format of this proxy file?
Please attach a sample file for reference. Thanks

**Comment by OGSegu** [comment]
Just a default proxy IP:PORT

**Comment by toxicFAN** [comment]
nah it says wron proxy file.

**Comment by OGSegu** [comment]
Could you please send me your proxies and error message

**Comment by toxicFAN** [comment]
I think main question is, what proxy do you used while developing the tool? I guess you are using proxy to make http requests unique while connecting to twitch. What proxy SW are you using?

**Comment by OGSegu** [comment]
It was working with public HTTPS proxies

**Comment by toxicFAN** [comment]
perhaps its lame, but coudl you provide at least one which worked for you? I tried using a few publicly available proxy servers and none worked for me here :(
Please provide the nam of it, list of proxies whch worked or at least the one worked for you. Thank you, best regards

**Comment by toxicFAN** [comment]
btw i used a few https proxies from spys.one and im always getting "Viewers sent 0" . No longer error that bad proxy is given.
