### ISSUE TITLE
Bad proxy

### ISSUE THREAD

**Issue by BoXNoX** [OGSegu/Twitch-View-Bot#23]
Hey there. 
Whenever I run the snapshot and load the proxies in and send them to work I always get a "Bad proxy" message for every single one of them, and the whole thing just doesn't work.
What am I doing wrong?

**Comment by SantiParris8** [comment]
You are doing nothing wrong, your proxies just dot work

**Comment by OGSegu** [comment]
@SantiParris8 gave you an answer
