### ISSUE TITLE
I need help)) Project : => no module-info.java found

### ISSUE THREAD

**Issue by ulitee89malkuriyaa** [OGSegu/Twitch-View-Bot#25]
Hi bro! 
i need help a bit.
Please help me solve this problem
I indicated the path, then I entered the command you specified, but I got this error: 

![AAAAAAAAAAAAAAAA](https://user-images.githubusercontent.com/85231555/120475537-7bc58980-c377-11eb-8adb-0fe63016d816.png)

**Comment by rydelek111** [comment]
me to help !!!

**Comment by SantiParris8** [comment]
Thats not an error, thats a succesful build, the contents of the build are dound in biuld/libs

**Comment by OGSegu** [comment]
Solved by @SantiParris8
