### ISSUE TITLE
Temporary count-up?

### ISSUE THREAD

**Issue by gogproxy** [OGSegu/Twitch-View-Bot#26]
Can the number of viewers be retained only temporarily?

**Comment by gogproxy** [comment]
Is this temporary? 
I tried to move it, but the number of viewers increased only temporarily.

**Comment by gogproxy** [comment]
ahh Runnable getExecutable
Thread.sleep(XXXXXX)!
?

**Comment by OGSegu** [comment]
Still didn't find out how to make it not temporarily. Working on it.

**Comment by SantiParris8** [comment]
With good proxies the bot works like a charm, residential proxies get banned afer about 20minutes but use rotating proxies
