### ISSUE TITLE
Erros build 

### ISSUE THREAD

**Issue by rydelek111** [OGSegu/Twitch-View-Bot#32]
![image](https://user-images.githubusercontent.com/79153428/121753879-8f10eb80-cb13-11eb-823a-851e55fa3e53.png)

Do you know what i did wrong ?

**Comment by SantiParris8** [comment]
I dont know what  went weong, you can try using a google collab i made to build gradle without having the correct enviroment locally. 

from google.colab import drive

drive.mount("/content/gdrive")

!ls

!git clone https://github.com/OGSegu/Twitch-View-Bot


%cd Twitch-View

!chmod 755 -R ./gradlew

!./gradlew build

!ls

**Comment by SantiParris8** [comment]
https://github.com/SantiParris8/Twitch-View-Bot/blob/master/.github/workflows/gradle.yml

**Comment by rydelek111** [comment]
yes @OGSegu working great but i need good proxy https , but your build didnt work for me :)

**Comment by SantiParris8** [comment]
I might have a mistake in my gradle configuration. I will  upload it again later. You should search for good residential proxys to have the most stable proxies.

**Comment by rydelek111** [comment]
> Mogę mieć błąd w konfiguracji Gradle. Wrzucę go ponownie później. Aby mieć najbardziej stabilne proxy, powinieneś szukać dobrych serwerów proxy.

oke thanks i will wait :) and I had a lot of HTTPS proxies and I had sent but the audience did not come, I know you have to buy private ones but you know where? or do you know where I get it for free?

**Comment by SantiParris8** [comment]
For private proxies to work you have to buy them, and the best ones are not cheap. I used brightstar, but any proxy provider should work, just make using you are using thebest ones they have. Try looking for residential proxies, not ISP, isp proxies wont work.

**Comment by rydelek111** [comment]
> For private proxies to work you have to buy them, and the best ones are not cheap. I used brightstar, but any proxy provider should work, just make using you are using thebest ones they have. Try looking for residential proxies, not ISP, isp proxies wont work.

Ok thank you , 

my last question is it possible to convert this project to socks5?

**Comment by SantiParris8** [comment]
Yes, this is how you dot it: https://stackoverflow.com/questions/22937983/how-to-use-socks-5-proxy-with-apache-http-client-4

**Comment by rydelek111** [comment]
> Yes, this is how you dot it: https://stackoverflow.com/questions/22937983/how-to-use-socks-5-proxy-with-apache-http-client-4

oke thanks i will try todday , 

with your version i get errors with java . what version are you using java? and gradle?

**Comment by Kuhicop** [comment]
bro, you have to use this: jdk-11.0.10

you can see at error "class file major version 60"

download here: https://www.oracle.com/es/java/technologies/javase/jdk11-archive-downloads.html

**Comment by rydelek111** [comment]
> bro, you have to use this: jdk-11.0.10
> 
> you can see at error "class file major version 60"
> 
> download here: https://www.oracle.com/es/java/technologies/javase/jdk11-archive-downloads.html

Yes this is fixed but second error is upp

**Comment by Kuhicop** [comment]
That version is wrong, at this line:
viewBot = new ViewBot(this, proxyQueue, target);

The ViewBot constructor is taking as first parameter the class: ControllerMain
![image](https://user-images.githubusercontent.com/27239965/121782532-1c068400-cbaa-11eb-86ee-c2e8a1e7aa3d.png)

Here it's sending as first parameter the class: Controller

So of course it will break

**Comment by SantiParris8** [comment]
I alredy said my version is not stable, that why its not merged, please use OGSegus version.

**Comment by SantiParris8** [comment]
@OGSegu you may close this issue since there is no actual real error.
