### ISSUE TITLE
Buid failed

### ISSUE THREAD

**Issue by isvktt** [OGSegu/Twitch-View-Bot#37]
![00](https://user-images.githubusercontent.com/64146745/123502680-99a7a680-d624-11eb-8d70-9f163b930b0a.png)

this is appearing, what can it be?

**Comment by OGSegu** [comment]
Scroll to the top. I can't see the main issue.

**Comment by isvktt** [comment]
![11](https://user-images.githubusercontent.com/64146745/123520109-76611380-d685-11eb-9266-61f5a3111619.png)
