### ISSUE TITLE
any ideas about viewers retention?

### ISSUE THREAD

**Issue by KiraSokolov** [OGSegu/Twitch-View-Bot#38]
Well, it works with private proxy, but after ~min no vierwers :c 
![image](https://user-images.githubusercontent.com/6352214/123519527-74fb0f80-d6b4-11eb-9e23-2215f2971e6d.png)
![image](https://user-images.githubusercontent.com/6352214/123519523-6c0a3e00-d6b4-11eb-8cd1-a610fb9c1cf4.png)

**Comment by OGSegu** [comment]
Did you use residential one ?

**Comment by OGSegu** [comment]
![изображение](https://user-images.githubusercontent.com/51200522/123519583-e76bef80-d6b4-11eb-829d-04bb2e92906b.png)

It works great with these type of proxies.

**Comment by KiraSokolov** [comment]
did you mean changing every 10 minutes or what?

**Comment by OGSegu** [comment]
Google what does "rotating residential proxies" mean
