### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LaG4** [OGSegu/Twitch-View-Bot#40]
Your program has stopped working.
Excuse me. it's my fault.

I modified your program
I made a program to hold Viewer in Python
Your program will do the same because it has been dealt with.
It's stuck.

**Comment by LaG4** [comment]
Is there another approach?
Or do you want to end it?

**Comment by LaG4** [comment]
By the way, Viewer can be easily held
I'll give you the Python code.
You will know immediately. : D

I take a different approach. I support you

         with requests.Session () as s:
             while True:
                 http_client = m3u8.httpclient.DefaultHTTPClient (proxies)
                 playlist = m3u8.load (url, http_client = http_client)

**Comment by LaG4** [comment]
It started moving again
To block my program
Twitch made a fix, but it looks like it was a very bad fix.

**Comment by LaG4** [comment]
Your program may stop working
There is no doubt that the other side is currently taking measures
It wasn't working 5 hours ago
I made a very bad fix by fixing it over there and fixing it here as well

If you advise
All you have to do is always load m3u8 to keep the Viewer

However, your program is peaky and will quickly block the proxy.
Should be modified to access a little more randomly

**Comment by OGSegu** [comment]
#38
