### ISSUE TITLE
Build Error | A problem occurred evaluating root project

### ISSUE THREAD

**Issue by Hovsep90** [OGSegu/Twitch-View-Bot#43]
Greetings, can you please help me with this error?

![image](https://user-images.githubusercontent.com/11386801/126999493-ad4a6054-b998-4339-91e5-2cd23dbf5b9f.png)

**Comment by Janloui** [comment]
hi i'm having the same issue. Did you find a solution ?

**Comment by Janloui** [comment]
Ok i found it : replace testCompile by testImplementation
so gradle load properly.
Now i'm having an issue when i do : gradle build

**Comment by Hovsep90** [comment]
@Janloui Thank you !!!
